// eslint-disable-next-line import/no-anonymous-default-export
export default {
  requiredField: "Zorunlu Alan",
  atLeastEightCharacters: "En az 8 Karakter Girilmeli",
  corpText: "Teknik Apre Corp.",
  adminPanelLogin: "Admin Panel Giriş",
  signIn: "Giriş Yap",
  emailOrUsername: "Email / Kullanıcı Adı",
  password: "Şifre",
  teknikapre: "teknikapre",
  logout: "Çıkış Yap",
  login: "Giriş Yap",
  parties: "Partiler",
  partiesFetchError: "Partiler yüklenemedi!",
  search: "Arama...",
  reload: "Yenile",
  name: "İsim",
  net_weight_division_num: "Metre Kaça Bölünecek?",
  gross_weight_addition_num: "Net Kiloya Kaç Eklenecek?",
  template_img: "Şablon Resmi",
  operations: "İşlemler",
  update: "Güncelle",
  delete: "Sil",
  createParty: "Parti Oluştur",
  details: "Detaylar",
  viewDetails: "Detayları Görüntüle",
  partyDetailsError: "Parti detayları yüklenemedi!",
  partyUpdateSuccess: "Parti başarıyla güncellendi!",
  partyUpdateError: "Parti güncellenirken bir hata oluştu!",
  partyDeleteConfirm: "Bu partiyi silmek istediğinize emin misiniz?",
  partyDeleteSuccess: "Parti başarıyla silindi!",
  partyDeleteError: "Parti silinirken bir hata oluştu!",
  backToParties: "Partilere Dön",
  save: "Kaydet",
  cancel: "İptal Et",
  deleteParty: "Partiyi Sil",
  partyLineItemsError: "Partinin itemleri yüklenemedi!",
  openBarcode: "Barkodu Aç",
  rollNo: "Roll No",
  partyLineItemDeleteSuccess: "Parti item başarıyla silindi!",
  partyLineItemDeleteError: "Parti item silinirken bir hata oluştu!",
  createExcelFileError: "Excel dosyası oluşturulurken bir hata meydana geldi!",
};
