// eslint-disable-next-line import/no-anonymous-default-export
export default {
  requiredField: "Zorunlu Alan",
  atLeastEightCharacters: "En az 8 Karakter Girilmeli",
  corpText: "Teknik Apre Corp.",
  adminPanelLogin: "Admin Panel Giriş",
  signIn: "Giriş Yap",
  emailOrUsername: "Email / Kullanıcı Adı",
  password: "Şifre",
  teknikapre: "teknikapre",
  logout: "Çıkış Yap",
  login: "Giriş Yap",
  parties: "Partiler",
  partiesFetchError: "Partiler yüklenemedi!",
  search: "Arama...",
  reload: "Yenile",
  name: "İsim",
  net_weight_division_num: "Metre Kaça Bölünecek?",
  gross_weight_addition_num: "Net Kiloya Kaç Eklenecek?",
  template_img: "Şablon Resmi",
  operations: "İşlemler",
  update: "Güncelle",
  delete: "Sil",
};
