export const USER_AUTHENTICATING = "USER_AUTHENTICATING";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_AUTHENTICATION_HAS_ERROR = "USER_AUTHENTICATION_HAS_ERROR";

export const USER_FETCHING = "USER_FETCHING";
export const USER_FETCHED = "USER_FETCHED";
export const USER_FETCH_HAS_ERROR = "USER_FETCH_HAS_ERROR";
