export const USER_AUTHENTICATING = "USER_AUTHENTICATING";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_AUTHENTICATION_HAS_ERROR = "USER_AUTHENTICATION_HAS_ERROR";

export const USER_FETCHING = "USER_FETCHING";
export const USER_FETCHED = "USER_FETCHED";
export const USER_FETCH_HAS_ERROR = "USER_FETCH_HAS_ERROR";

export const PARTIES_FETCHING = "PARTIES_FETCHING";
export const PARTIES_FETCHED = "PARTIES_FETCHED";
export const PARTIES_FETCH_HAS_ERROR = "PARTIES_FETCH_HAS_ERROR";

export const PARTY_FETCHING = "PARTY_FETCHING";
export const PARTY_FETCHED = "PARTY_FETCHED";
export const PARTY_FETCH_HAS_ERROR = "PARTY_FETCH_HAS_ERROR";

export const PARTY_UPDATING = "PARTY_UPDATING";
export const PARTY_UPDATED = "PARTY_UPDATED";
export const PARTY_UPDATE_HAS_ERROR = "PARTY_UPDATE_HAS_ERROR";

export const PARTY_DELETING = "PARTY_DELETING";
export const PARTY_DELETED = "PARTY_DELETED";
export const PARTY_DELETE_HAS_ERROR = "PARTY_DELETE_HAS_ERROR";

export const PARTY_LINE_ITEMS_FETCHING = "PARTY_LINE_ITEMS_FETCHING";
export const PARTY_LINE_ITEMS_FETCHED = "PARTY_LINE_ITEMS_FETCHED";
export const PARTY_LINE_ITEMS_FETCH_HAS_ERROR =
  "PARTY_LINE_ITEMS_FETCH_HAS_ERROR";

export const PARTY_LINE_ITEM_DELETING = "PARTY_LINE_ITEM_DELETING";
export const PARTY_LINE_ITEM_DELETED = "PARTY_LINE_ITEM_DELETED";
export const PARTY_LINE_ITEM_DELETE_HAS_ERROR =
  "PARTY_LINE_ITEM_DELETE_HAS_ERROR";
